### ISSUE TITLE
add_checker is deprecated in watir-webdriver

### ISSUE THREAD

**Issue by melnikaite** [watir/watir-rails#18]
I'm getting warning `Browser#add_checker is deprecated. Use Browser#after_hooks#add instead.`
https://github.com/watir/watir-webdriver/blob/f5e67b4335d69cd886628dd9c643d2bc5cb56084/lib/watir-webdriver/browser.rb#L289

**Comment by jarmo** [comment]
Thanks for reporting. We're happily accepting pull requests.

**Comment by jarmo** [comment]
Fixed in version 1.2.1.
