### ISSUE TITLE
Timeout::Error when booting up 

### ISSUE THREAD

**Issue by shuriu** [watir/watir-rails#26]
So for some reason, on my machine on MacOS Mojave 10.14.6 (18G5033) line `lib/watir/rails.rb:110` throws a timeout error when ran for the first time.

https://github.com/watir/watir-rails/blob/0185e7a044839b4252c84e969eeb6fc4c65d8a38/lib/watir/rails.rb#L107-L117

It seems that when checking if a server is actually running, the port number is discarded on the initial call.

Doing `Net::HTTP.start('127.0.0.1', nil) { block }` without a port number, picks port number 80 by default. But for some weird reason OSX already has something running on this port and then the whole call hangs with a timeout error.

**Comment by jarmo** [comment]
Nice catch! You probably have some web-server running (nginx/apance?). It's interesting that no-one else has stumbled upon this problem all these years.

Anyway, thanks - your PR has been merged and a gem version of 2.2.2 has been released.
