### ISSUE TITLE
NameError VERSION

### ISSUE THREAD

**Issue by rjaus** [watir/watir-rails#32]
```
require 'watir'
require 'webdrivers'
browser = Watir::Browser.new :firefox
```
Results in:
```
Traceback (most recent call last):
        2: from (irb):4
        1: from (irb):4:in `new'
NameError (uninitialized constant Watir::VERSION)
```

I'm not sure what I'm doing wrong, but it all seems to work when I use `gem watir` rather than this rails integration.

**Comment by jarmo** [comment]
Why do you think that this is even related to watir-rails? In you code example I don't see that you've required `watir-rails`. It might be related to the require statements in your code examples and not watir-rails.

**Comment by rjaus** [comment]
I assumed it was related to watir-rails, as it only occurs when I have that gem installed.  If I remove watir-rails and install `watir` it works as expected.

I tested `watir -rails` on a Rails 5 project and it works as expected, I'm only seeing this issue in Rails 6.1.3.

Let me dig a little deeper and work out what's going on.  I'll re-open if I get anywhere

**Comment by aaron-humerickhouse** [comment]
I had this issue in watir. I had to require version in watir/lib/watir/http_client

**Comment by aaron-humerickhouse** [comment]
I think this is worth re-opening @rjaus 

```
❯ pry
[1] pry(main)> require 'watir'
true
[2] pry(main)> require 'webdrivers'
true
[3] pry(main)> browser = Watir::Browser.new
NameError: uninitialized constant Watir::VERSION
from /Users/aaron/.rvm/gems/ruby-2.6.5/gems/watir-7.0.0.beta2/lib/watir/http_client.rb:4:in `request'
[4] pry(main)> exit

❯ gem uninstall watir-rails
Successfully uninstalled watir-rails-2.2.2

❯ pry
[1] pry(main)> require 'watir'
true
[2] pry(main)> require 'webdrivers'
true
[3] pry(main)> browser = Watir::Browser.new
#<Watir::Browser:0x4e3687e47280a50a url="data:," title="">```

**Comment by jarmo** [comment]
Can you also try the same failing code without requiring `webdrivers` just to be on the safe side that this does not affect it?

@titusfortner as I understand then you've been more involved with `watir-7` - do you have any ideas why this situation might happen? I don't see `watir-rails` itself trying to look for `Watir::VERSION`, but maybe `Watir::HttpClient` gets confused when `watir-rails` is loaded somehow?

**Comment by aaron-humerickhouse** [comment]
This happened in watir 6.19.1 also

**Comment by jarmo** [comment]
@aaron-humerickhouse

1) did you try the same code without loading `webdrivers`?
2) your example with pry - I don't understand how does `watir-rails` even get loaded in that example? Can you explain that?

**Comment by aaron-humerickhouse** [comment]
```
❯ pry
[1] pry(main)> require 'watir'
true
[2] pry(main)> browser = Watir::Browser.new
NameError: uninitialized constant Watir::VERSION
from /Users/aaron/.rvm/gems/ruby-2.6.5/gems/watir-7.0.0.beta2/lib/watir/http_client.rb:4:in `request'
[3] pry(main)> exit

❯ gem uninstall watir-rails
Successfully uninstalled watir-rails-2.2.2

❯ pry
[1] pry(main)> require 'watir'
true
[2] pry(main)> browser = Watir::Browser.new
#<Watir::Browser:0x4bf67de3adff274 url="data:," title="">
```


`I don't understand how does watir-rails even get loaded in that example? Can you explain that?` 
I can't, but it clearly made a difference which is bizarre

**Comment by jarmo** [comment]
Can you try this code instead and nothing else:

```ruby
require 'watir-rails'
browser = Watir::Browser.new
```

**Comment by aaron-humerickhouse** [comment]
```bash
❯ gem install watir-rails
Successfully installed watir-rails-2.2.2
Parsing documentation for watir-rails-2.2.2
Installing ri documentation for watir-rails-2.2.2
Done installing documentation for watir-rails after 0 seconds
1 gem installed
```
```ruby
❯ pry
[1] pry(main)> require 'watir-rails'
LoadError: cannot load such file -- watir-rails
from (pry):1:in `require'
```

**Comment by jkotests** [comment]
Looks like using Watir-Rails now requires `watir/rails` not `watir-rails`.

I believe the problem is a file naming conflict between Watir and Watir-Rails. Both include a `watir/version.rb` file. Depending on which gem is loaded first or the load path, `require 'watir'` could ended up loading Watir-Rail's version file instead.

Moving the `watir/version.rb` to `watir/rails/version.rb` would hopefully solve this issue.

**Comment by jarmo** [comment]
@jkotests that could be actually it! However, I'm confused as to why this problem started to appear just now? File structure in `watir-rails` has been like that from the beginning. @titusfortner Did watir 7 introduce `watir/version.rb` file and that's the reason why this problem has not appeared before?

**Comment by jarmo** [comment]
Released `watir-rails 2.2.3` with the proposed change by @jkotests. Please give it a try and let me know if it fixed the problem. @jkotests thank you for your (possible) solution!

**Comment by jkotests** [comment]
@jarmo , Watir started requiring `watir/version` in v6.19.0, which was released in Mar 12, 2021 (https://github.com/watir/watir/commit/d9c1586678765d5e2300abf9eee8446551fc7c60). So the conflict is quite new.

**Comment by jarmo** [comment]
@jkotests thanks for clarification!

**Comment by aaron-humerickhouse** [comment]
Solved
